index:
    path: /
    controller: App\Controller\DefaultController
chuck:
    path: /chuck
    controller: App\Controller\ChuckController
orders_list:
    path: /orders
    controller: App\Controller\OrdersList
    methods: ["GET"]
orders_detail:
    path: /orders/{id}
    controller: App\Controller\OrdersDetail
    methods: ["GET"]
order_update_status:
    path: /orders/{id}/status/{status}
    controller: App\Controller\OrderUpdateStatus
